name: Static Analysis

on:
  push:
    branches: [ "*" ]
    paths:
      - 'petstore-feature5-backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - 'petstore-feature5-backend/**'

env:
  JAVA_VERSION: '21'
  WORKING_DIRECTORY: 'petstore-feature5-backend'

jobs:
  static-analysis:
    name: Run Static Code Analysis
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'
          cache-dependency-path: '${{ env.WORKING_DIRECTORY }}/pom.xml'

      - name: Build project (compile only)
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn -B clean compile -Dmaven.test.skip=true

      - name: Run Checkstyle
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn checkstyle:checkstyle -Dmaven.test.skip=true --batch-mode

      - name: Run PMD
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn pmd:pmd -Dmaven.test.skip=true --batch-mode

      - name: Run SpotBugs
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.8.3.0:spotbugs -Dmaven.test.skip=true --batch-mode

      # 📦 Subida de artefactos
      - name: Upload Checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: ${{ env.WORKING_DIRECTORY }}/target/checkstyle-result.xml

      - name: Upload PMD reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-reports
          path: ${{ env.WORKING_DIRECTORY }}/target/pmd.xml

      - name: Upload SpotBugs reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: ${{ env.WORKING_DIRECTORY }}/target/spotbugsXml.xml
